Update patch set 1
Patch Set 1:

ImportError: No module named ipaddress  (during check) 

We'll need to add python-ipaddress as requires and BR. On it.

Patch-set: 1
Reviewer: Gerrit User 113 <113@270e2033-b340-4cff-9539-693957ebf0e7>
Label: Code-Review=0